Repository hambrientoapp/hambrientoapp, pull requests merged in 2019-10, with the labels that each got.

#8 Feature/about page
  src/App.js
  src/pages/About.js
Labels: Hacktoberfest, public

#10 Update changes
  src/App.js
  src/pages/About.js
  src/pages/Contact.js
Labels: public

#12 feat(public): category section #7
  src/components/Categories.js
Labels: Hacktoberfest, public

#13 Update master
  src/components/Categories.js
Labels: public

#23 Update about page
  src/pages/About.js
Labels: Front-end, Hacktoberfest

#25 feat(front): updated about page issue #21
  src/pages/About.js
Labels: Front-end, Hacktoberfest

#26 Issue #18
  src/pages/About.js
Labels: Front-end, Hacktoberfest

#27 About Enrique Pino
  .gitignore
  package-lock.json
  src/pages/About.js
Labels: Front-end, Hacktoberfest

#28 Commit HacktoberFest
  src/pages/About.js
Labels: Front-end, Hacktoberfest

#34 creating contribution page and adding it to react router
  src/App.js
  src/pages/Contribution.js
Labels: Front-end, Hacktoberfest

#35 Added Report.js
  src/components/Report.js
Labels: Front-end, Hacktoberfest

#37 📝Add Evaluate Component
  src/App.js
  src/components/Evaluate.js
Labels: Front-end, Hacktoberfest

#42 Feature/helpers 40
  src/components/Places.js
Labels: Front-end, Hacktoberfest

#44 feat(front): Update About Page #17
  src/pages/About.js
Labels: Front-end, Hacktoberfest

#48 add icon hungry person in user position
  src/components/Places.js
  src/person.png
Labels: Front-end, Hacktoberfest

#49 added Dick's burgers in Seattle WA
  src/data/places.geojson
Labels: Hacktoberfest, data

#52 category venezuelan
  README.md
  src/components/Categories.js
  src/components/Places.js
  src/components/ReportForm.js
  src/data/places.js
Labels: Front-end, Hacktoberfest

#53 Data p laces
  src/data/places.geojson
  src/data/places.js
Labels: Hacktoberfest, data

#54 Feat/add new category
  README.md
  src/components/Categories.js
  src/components/ReportForm.js
Labels: Front-end, Hacktoberfest

#56 like food
  src/components/Contador.js
  src/pages/Home.js
Labels: Front-end, Hacktoberfest

#64 Feature/back
  back/.gitignore
  back/index.js
  back/package-lock.json
  back/package.json
  front/.gitignore
  front/package.json
  front/public/favicon.ico
  front/public/index.html
  front/public/logo192.png
  front/public/logo512.png
  front/public/manifest.json
  front/public/robots.txt
  front/src/App.css
  front/src/App.js
  front/src/App.test.js
  front/src/components/Categories.js
  front/src/components/Contador.js
  front/src/components/Evaluate.js
  front/src/components/Footer.js
  front/src/components/Header.js
  front/src/components/Menu.js
  front/src/components/Picada.js
  front/src/components/Places.js
  front/src/components/Report.js
  front/src/components/ReportForm.js
  front/src/components/Search.js
  front/src/data/places.geojson
  front/src/data/places.js
  front/src/index.css
  front/src/index.js
  front/src/logo.svg
  front/src/pages/About.js
  front/src/pages/Contact.js
  front/src/pages/Contribution.js
  front/src/pages/Home.js
  front/src/person.png
  front/src/serviceWorker.js
  package-lock.json
Labels: Back-end, Front-end, Hacktoberfest

#66 corrected spelling and typos in readme.md file - #hacktoberfest
  README.md
Labels: Hacktoberfest, documentation
